apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: open-helpers
  region: us-west-2

managedNodeGroups:
  - name: helper1
    labels: { releaseName: h1 }
    instanceType: t3.medium
    desiredCapacity: 1
  - name: helper2
    labels: { releaseName: h2 }
    instanceType: t3.medium
    desiredCapacity: 1
  - name: helper3
    labels: { releaseName: h3 }
    instanceType: t3.medium
    desiredCapacity: 1

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true

addons:
  - name: aws-ebs-csi-driver
    wellKnownPolicies: # Adds an IAM service account
      ebsCSIController: true
      
cloudWatch:
 clusterLogging:
   enableTypes: ["*"]
   logRetentionInDays: 30
