apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  network.toml: |
{{ .Files.Get "config/network.toml" | indent 4 }}
  tls.pem: |
{{ printf "config/%s.pem" .Release.Name | .Files.Get | indent 4 }}
  mk.pub: |
{{ printf "config/%s_mk.pub" .Release.Name | .Files.Get | indent 4 }}