kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-ghcr
  labels:
    app: {{ .Release.Name }}-helper
stringData:
  .dockerconfigjson: |
{{ .Files.Get "config/ghcr_auth.json" | indent 4 }}

