apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pubcerts
data:
{{- $files := .Files }}
{{- $id := trimPrefix "h" .Release.Name }}
{{- range $ix := until (int $.Values.shardCount) }}
  {{- $path := "config/helper%s/shard%d/h%s-helper-shard-%d.h%s-helper-shard.default.svc.cluster.local%s"  }}
  shard-{{ $ix }}.pem: |-
    {{- $pem_path := printf $path $id $ix $id $ix $id ".pem"  }}
{{$files.Get $pem_path | indent 4 }}
  shard-{{ $ix }}_mk.pub: |-
    {{- $mk_pub_path := printf $path $id $ix $id $ix $id "_mk.pub"  }}
{{$files.Get $mk_pub_path | indent 4 }}
{{- end }}

