{{- if eq .Release.Name "h1" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-collector-deployment
  labels:
    app: report-collector
spec:
  selector:
    matchLabels:
      app: report-collector
  template:
    metadata:
      labels:
        app: report-collector
    spec:
      imagePullSecrets:
        - name: {{ .Release.Name }}-ghcr
      containers:
      - name: report-collector
        image: {{ .Values.rcImage }}
        imagePullPolicy: Always
        command: ["tail", "-f", "/dev/null"]
        volumeMounts:
          - name: {{ .Release.Name }}-configs
            mountPath: /etc/ipa
      volumes:
        - name: {{ .Release.Name }}-configs
          configMap:
            name: {{ .Release.Name }}-configmap
{{- else }}
# ignore this file
{{- end }}

