apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  tls.key: |
{{ printf "config/%s-cert.key" .Release.Name | .Files.Get | indent 4 }}
  mk.key: |
{{ printf "config/%s_mk.key" .Release.Name | .Files.Get | indent 4 }}