apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
{{- /* Inside the loop . scope gets overriden so we store files before */}}
{{- $files := .Files }}
{{- /* We store just the helper number (id) */}}
{{- $id := trimPrefix "h" .Release.Name }}
{{- range $ix := until (int $.Values.shardCount) }}
  {{- /* Following is the expected path template for each shard config. */}}
  {{- $path := "config/helper%s/shard%d/h%s-helper-shard-%d.h%s-helper-shard.default.svc.cluster.local%s"  }}
  shard-{{ $ix }}.key: |-
    {{- /* We format the path, read it and indent it to match its location. */}}
{{ printf $path $id $ix $id $ix $id ".key" | $files.Get | indent 4 }}
  shard-{{ $ix }}_mk.key: |-
    {{- /* Same for match key */}}
{{ printf $path $id $ix $id $ix $id "_mk.key" | $files.Get | indent 4 }}
{{- end }}
