apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ips
spec:
# https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-helper-shard
  ports:
    - name: https
      port: {{ .Values.externalPort }}
