apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-helper-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-helper
  ports:
    - port: {{ .Values.port }}
      nodePort: {{ .Values.serviceNodePort }}