apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ips
spec:
# https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
  type: ClusterIP
  clusterIP: None
  externalName: {{ .Release.Name }}-ips
  selector:
    app: {{ .Release.Name }}-helper-shard
  ports:
    - name: mpc
      port: {{ .Values.mpcPort }}
    - name: shard
      port: {{ .Values.shardPort }}
